# Generated by Django 6.0.1 on 2026-02-04 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='ventas.empresas')),
            ],
            options={
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('cc_suc', models.PositiveIntegerField(unique=True)),
                ('compania', models.PositiveIntegerField()),
                ('nombre_sucursal', models.CharField(max_length=100)),
                ('fecha_inicio_suc', models.IntegerField(blank=True, null=True)),
                ('fecha_fin_suc', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_marca', models.ForeignKey(db_column='id_marca', on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='ventas.marcas')),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_dft', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_dft', models.IntegerField()),
                ('fecha', models.DateField()),
                ('periodo', models.CharField(blank=True, max_length=50, null=True)),
                ('semana', models.CharField(blank=True, max_length=50, null=True)),
                ('vtas_netas', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('iva_comedor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_iva_por_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('iva_llevar', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('vtas_comedor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('vtas_llevar', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('vtas_entrega', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('iva_entrega', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('iva_ventana', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('vtas_ventana', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('reembolso_cliente', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.sucursales')),
            ],
            options={
                'db_table': 'ventas',
                'indexes': [models.Index(fields=['fecha', 'id_sucursal'], name='ventas_fecha_2141ed_idx')],
            },
        ),
    ]
